name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-20.04
    outputs:
      version_changed: ${{ steps.check.outputs.changed }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current version from repository
        id: current_version
        run: |
          CURRENT_VERSION=$(grep 'CURRENT_VERSION' src/main/java/me/t3sl4/hydraulic/utils/general/SystemVariables.java | sed -E 's/.*"v([0-9]+\.[0-9]+\.[0-9]+)".*/\1/')
          echo "version=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Get latest release version
        id: latest_version
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/hidirektor/ondergrup-hydraulic-tool/releases/latest | jq -r '.tag_name' | sed 's/v//')
          echo "latest=$LATEST_VERSION" >> $GITHUB_ENV

      - name: Compare versions
        id: check
        run: |
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "changed=true" >> $GITHUB_ENV
            echo "changed=true"
          else
            echo "changed=false" >> $GITHUB_ENV
            echo "changed=false"
          fi

  macos-build:
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true'
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project (MacOS)
        run: mvn clean package

      - name: Rename JAR file (MacOS)
        run: |
          JAR_FILE=$(find target -name "*.jar" | head -n 1)
          mv "$JAR_FILE" macos_Hydraulic.jar

      - name: Upload artifact (MacOS)
        uses: actions/upload-artifact@v3
        with:
          name: macos_Hydraulic
          path: macos_Hydraulic.jar

  unix-build:
    needs: macos-build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project (Ubuntu)
        run: mvn clean package

      - name: Rename JAR file (Ubuntu)
        run: |
          JAR_FILE=$(find target -name "*.jar" | head -n 1)
          mv "$JAR_FILE" unix_Hydraulic.jar

      - name: Upload artifact (Ubuntu)
        uses: actions/upload-artifact@v3
        with:
          name: unix_Hydraulic
          path: unix_Hydraulic.jar

  windows-build:
    needs: unix-build
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project (Windows)
        run: mvn clean package

      - name: Rename JAR file (Windows)
        run: |
          $JAR_FILE = Get-ChildItem -Path target -Filter *.jar | Select-Object -First 1
          Move-Item -Path $JAR_FILE.FullName -Destination ondergrup-hydraulic-tool.jar -Force

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v3
        with:
          name: windows_Hydraulic
          path: ondergrup-hydraulic-tool.jar

  release:
    needs: [macos-build, unix-build, windows-build]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Prepare artifacts for release
        run: |
          mkdir -p artifacts
          mv macos_Hydraulic/macos_Hydraulic.jar artifacts/
          mv unix_Hydraulic/unix_Hydraulic.jar artifacts/
          mv windows_Hydraulic/windows_Hydraulic.exe artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          name: v${{ env.version }} - Yeniliklerle Dolu Bir Deneyim! 🚀
          body: |
            Sevgili kullanıcılarımız,
            
              Bu güncelleme ile uygulamamızı daha güçlü, daha hızlı ve daha kullanıcı dostu hale getirdik. İşte sizler için sunduğumuz yenilikler:
            
              ✨ Yeni Özellikler:
              - Performans Artışı: Daha hızlı yüklenme süreleri ve optimize edilmiş işlem kapasitesi.
              - Yeni Arayüz Tasarımı: Modern ve minimalist tasarım ile daha sezgisel bir kullanıcı deneyimi.
              - Gelişmiş Bildirim Sistemi: Önemli güncellemelerden anında haberdar olun.
            
              🔧 Hata Düzeltmeleri ve İyileştirmeler:
              - Küçük hatalar giderildi ve genel sistem kararlılığı artırıldı.
              - Geri bildirimlerinizi dikkate alarak kullanıcı deneyimini geliştirdik.
            
              💡 Yeni Eklenen Özellikler:
              - Karanlık Mod: Göz dostu bir deneyim için karanlık tema seçeneği eklendi.
              - Çoklu Dil Desteği: Artık birden fazla dilde hizmet sunuyoruz!
            
              Bize destek olduğunuz için teşekkür ederiz. Sizlerin geri bildirimleriyle her geçen gün daha iyiye gidiyoruz. Yeni sürümümüzü hemen keşfedin!
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.SETUP_TOKEN }}